export type {
  CreateVehicleInput,
  FuelConsumptionSource,
  InsuranceStatus,
  TireType,
  UpdateVehicleInput,
  VehicleFuelConsumptionInfo,
  VehicleInsuranceInfo,
  VehicleLatestMilestoneInfo,
  VehicleNextMaintenanceInfo,
  VehiclePurchaseInfo,
  VehicleSaleInfo,
  VehicleSpecs,
  VehicleSpecsPromptParams,
  VehicleUserInfo,
  VehicleWithOwner,
} from './vehicle.types';
