export const TireConstraints = {
  BRAND_MIN: 1,
  BRAND_MAX: 50,

  MODEL_MIN: 1,
  MODEL_MAX: 50,

  WIDTH_MIN: 100,
  WIDTH_MAX: 400,

  ASPECT_RATIO_MIN: 20,
  ASPECT_RATIO_MAX: 90,

  RIM_DIAMETER_MIN: 10,
  RIM_DIAMETER_MAX: 24,

  PRICE_MIN: 0,

  STORAGE_LOCATION_MAX: 200,

  MILEAGE_AT_PURCHASE_MIN: 0,

  QUANTITY_MIN: 1,
  QUANTITY_MAX: 10,
  QUANTITY_DEFAULT: 4,
} as const;
